//
// Created by tomsgu on 5/19/17.
//

#ifndef BOMBERMAN_INVALIDCONFIGURATIONEXCEPTION_H
#define BOMBERMAN_INVALIDCONFIGURATIONEXCEPTION_H
class InvalidConfigurationException{};
#endif //BOMBERMAN_INVALIDCONFIGURATIONEXCEPTION_H
