//
// Created by tomsgu on 5/20/17.
//

#ifndef BOMBERMAN_OBJECTALREADYEXISTSEXCEPTION_H
#define BOMBERMAN_OBJECTALREADYEXISTSEXCEPTION_H
class ObjectAlreadyExistsException{};
#endif //BOMBERMAN_OBJECTALREADYEXISTSEXCEPTION_H
